/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_so_strtohex_SToH */

#ifndef _Included_com_so_strtohex_SToH
#define _Included_com_so_strtohex_SToH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_so_strtohex_SToH
 * Method:    dataServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_so_strtohex_SToH_dataServer
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_so_strtohex_SToH
 * Method:    dataTest
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_so_strtohex_SToH_dataTest
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_so_strtohex_SToH
 * Method:    StrToHexC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_so_strtohex_SToH_StrToHexC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
